### ISSUE TITLE
PROJECT III ESS

### ISSUE THREAD

**Issue by zalattarkada** [Ironhack-data-bcn-feb-2023/project-III-pipelines#1]
https://github.com/zalattarkada/Project-2-ESS/issues/new

**Comment by carlajsv** [comment]
Hola Zaka 👋🏾

Te dejo los comentarios del proyecto:

>## **Organización de los archivos🧹**

Excelente organización de los archivos. Lo único que agregaría es que los archivos dentro de la carpeta src pueden ir dentro de "code", es mejor y asi tienes menos carpetas. Gracias por seguir las instrucciones.

>## **README.md ✍🏽**

Zaka, excelente que hayas descrito las carpetas de tu repositorio muy buen valor añadido y tiene mucha importancia a la hora de revisarlo.

Está muy bien explicado y concreto el README, le agregaría algunos gráficos importantes para intentar explicar un poco mas a detalle el procedimiento que seguiste, pero muy muy bien.

>## **The code < > 👨🏽‍💻**

### cleaness.ipynb

Recuerda porfa comentar un poco mas los procedimientos que realices

### cleanpib.ipynb

Al igual que en el archivo anterior, recuerda comentar un poco más

Estos archivos podían ir en uno solo, no hace falta tener dos archivos de limpieza, puedes quizas dividir el procedimiento en dos.

### analysis.ipynb

Es importante tener un contexto de qué significa cada nomenclatura de tu archivo.

Con respecto al test de Mann-Whitney U, yo revisaría el parámetro alternative='less', no estoy segura de que la distribución de imdfetn sea siempre menor que la de imsmetn, comentame y lo vemos. Sin embargo, me gustó que hayas investigado y lo hayas hecho.

Hay muchos procedimientos que se repiten muchas veces, esto es parte de lo que se debe modularizar. Cuando repites líneas de código muchas veces, es un indicativo de que quizás ahi debe ir una función.


> ## **Visualizaciones 🎨**

Importante mantener una uniformidad en cuanto a colores, es decir, elige una paleta de colores para tus gráficos, por ejemplo, todos azules y naranja (o los que tu elijas), tambieén mantener un mismo idioma en todo el proyecto.

El gráfico de los boxplots de la perspectiva sobre inmigracion por pais no aportamucho, no se puede leer correctamente, yo lo quitaría o simplemente le daría una  vuelta.

>## **General**

En general creo que se puede mejorar mucho con respecto a gráficos, sin emabrgo me gustó mucho tu proyecto y como lo enfocaste, me gustaría que hablaramos mas a fondo de los errores que tuviste o los parámetros que no te salieron. Felicidades por tu proyecto.
