### ISSUE TITLE
PROJECTO 3 DANI 

### ISSUE THREAD

**Issue by dfnevar** [Ironhack-data-bcn-feb-2023/project-III-pipelines#11]
https://github.com/dfnevar/project-III-eda-etl.git

**Comment by carlajsv** [comment]
Hola Dani👋🏾

Te dejo los comentarios del proyecto:

>## **Organización de los archivos🧹**

Muy bien el colocar las carpetas que se mandaron en la descripción del proyecto. 

Recuerda que la carpeta de "my-code" es únicamente para archivos de de código. Las imagenes deben estar en la carpeta de imagenes

No entiendo mucho de que va cada archivo desde el comienzo, recuerda que el código debería estar modularizado y encapsulado.

>## **README.md ✍🏽**
Muy bien el README en general, me gustó la estructura que usaste, me llevó a entender tu idea de una vez.

Por otro lado, mas allá de la introducción al tema que trataste (que no está mal), que en este caso es los alquileres y el covid, es importante que en el README salga una breve explicación de que hay en cada archivo.

>## **The code < > 👨🏽‍💻**

### INTENTO DE SCRAPPING .ipynb

No entendí este archivo, creo que no aporta valor al proyecto.

### projecto 3.ipynb

Esta vez veo una mejora importante en cuanto a organización y comentarios del codigo, muy bien!

Recuerda qu elas funciones en las que encapsulas el código, se colocan en un archivo aparte, por lo general llamado src.py y se llaman en el otro archivo como si fuese una librería a exportar.

Los comentarios rojos de las funciones son para explicar lo que hacen las funciones y decir los parámetros que reciben. no deben haber comentarios azules para describir funciones, al menos de que quieras describir líneas de código específicas dentro de las funciones.

### sql-queries.sql

Este archivo tiene queries, pero no aporta mucho al proyecto, no se si al final hiciste algo con SQL.

> ## **Visualizaciones 🎨**

Recuerda que los ejes es mejor que sean para un único gráfico y que las etiquetas de los ejes no esten en 90 grados ni se solapen.

Usa guías para poder hacer que se entiendan mejor que etiqueta del eje corresponde con que punto del gráfico.

>## **General**
En general el proyecto esta mucho mas organizado que el anterior. Si te diría que aun le falta en cuanto a concordancia. A veces es mejor no incluir cosas que no aportan valor. Si quieres que este proyecto sea parte de tu portafolio, te recomendaría eliminar los archivos que no aportan valor y seguir los comentarios que te escribo aquí.

Muchas felicidaciones por tu proyecto y el esfuerzo invertido.
