### ISSUE TITLE
Project-III-Urska-DRAFT

### ISSUE THREAD

**Issue by urskakra** [Ironhack-data-bcn-feb-2023/project-III-pipelines#4]
Aún falta modularizacion etc ... Estoy en ello!

https://github.com/urskakra/project-2-vivino-UK

**Comment by carlajsv** [comment]
Hola Urska👋🏾

Te dejo los comentarios del proyecto:

>## **Organización de los archivos🧹**

Excelente organización de los archivos. Gracias por seguir las instrucciones del README del proyecto, está concreto y se por donde mepezar.

>## **README.md ✍🏽**

En el README es importante empezar con la descripción de las carpetas y archivos que tenemos en el Repo, es decir, ya que muchas veces los proyectos serán vistos por distintas personas y en general como buenas prácticas de github, es importante que el readme empiece con una pequeña descripción de ¿qué podemos encontrar en cada carpeta y en cada archivo?

Muy bien explicado todo en el README, me parece que la estructura que usaste estuvo acorde y tiene concordancia con el storitelling que desarrollates durante la exposición.

Me gustó mucho que incluyeras la variable de weather y que dieras contexto de ¿por qué es importante cuando hablamos de vinos?.

>## **The code < > 👨🏽‍💻**

### clean-files

- clean-meteo-catalunya.ipynb
- clean-meteo-duero.ipynb
- clean-wines.ipynb
- clean-meteo-rioja.ipynb

Estos cuatro archivos son muy sencillos, estaría muy bien resumirlo en uno solo, sobretodo porque el código que hay dentro no es tan complicado. También estaría guay haber modularizado y aunque están bastante resumidos, concretar más.

### analyze_wines.ipynb

Me gustó que hayas usado SQL para hacer reportes distintos.

Estaría guay que el código estuviese un poco mas estructurado. Recuerda que los comentarios azules son para comentar ciertas lineas de codigo (tal y como lo has hecho) pero los títulos están mejor en celdas tipo markdown

> ## **Visualizaciones 🎨**

Me ha gustado las visualizaciones que has elegido para mostrar en el README, sin embargo, revisaría las regresiones lineales que has aplicado. He visto que quizas las variables no son independientes, para graficar este tipo de cosas y poder ver correlación entre ellas, yo utilizaría un gráfico distinto.

No se por qué no has incluido las visualizaciones que están en los notebooks en el README, es porque están mal? en ese caso, es mejor no dejarlas y tener buena coherencia entre el readme y los notebooks.

>## **General**

En general te felicito por el Storytelling que hiciste, estuvo muy bien estructurado y correcto, asi como el proyecto, fue sencillo y concreto, a veces menos es más y diste en el punto. Muy bonito el tema que elegiste y las variables con las que lo quisiste relacionar. Felicitaciones!
