### ISSUE TITLE
Kevin Caminero

### ISSUE THREAD

**Issue by z3r0n1** [Ironhack-data-bcn-feb-2023/project-III-pipelines#5]
https://github.com/z3r0n1/project_stats

**Comment by carlajsv** [comment]
Hola Kevin, me di cuentra hoy que no subi tu feedback al proyecto.👋🏾

Te dejo los comentarios:

>## **Organización de los archivos🧹**

Muy bien la organizacion de los archivos, estan bien clasificados y nombrados, en cuanto a esto, muy bien.

>## **README.md ✍🏽**

Me gusto mucho que tu readme tenga la estructura del repositorio, me ayudo a ubicarme con respecto a las carpetas.

Recuerda mantener un único idioma en el readme y en general en todo el proyecto. Yo te recomiendo ingles.

Es mejor concretar mas en las ideas que quizas hacer el README tan largo. Por un lado el contexto esta super guay, sin embargo, es cierto que es un poco denso para algunas personas.

Guay que colocaste las imagenes mas importantes y el storytelling del readme esta muy bien estructurado.

>## **The code < > 👨🏽‍💻**

### src/main.ipynb

En general me gusto mucho que hayas comentado el código casi que linea a linea.

Recuerda no dejar las celdas abiertas al hacer commit, el documento se hace super largo para leer.

Hay muchas formas de simplifiacr los bucles, porfa trabajalos mas: por ejemplo, nbo hace falta crear uina variable para asignarle un 0 y luego usarlo en una comparación:

<img width="376" alt="Screenshot 2023-06-27 at 20 21 54" src="https://github.com/Ironhack-data-bcn-feb-2023/project-III-eda-etl/assets/100382807/0c0de1fe-1b42-41ad-b68b-6fd00e110d75">

Me gustó que te hayas tomado la molestia de hacer funciones, la proxima docuemntalas con comentarios y lo tendrías.

Esto tambien se puede poner dentro de funciones:

<img width="905" alt="Screenshot 2023-06-27 at 20 24 44" src="https://github.com/Ironhack-data-bcn-feb-2023/project-III-eda-etl/assets/100382807/7eb24551-4e7c-43de-b8a2-0e1af2d0c312">

Me gusto mucho que hayas hecho uso de clases, un bravo por eso.

> ## **Visualizaciones 🎨**

No encuentro relación en cuanto a todo el texto con los primeros graficos. por ejemplo, que son los products? accesorios que compras en el juego? creo recordar de la expo que esto es así, pero de buenas a primeras no esta fácil de entender. El precio que esta en los primeros graficos (los graficos interactivos) en que estan? en Euros?

Recuerda por favor no dejar los nombres por default que salen en los gráficos, muchas veces no se entienden.

En el gráfico de evolucion de la media de los cambios de precio por epoca estaría guay tener mas particiones en el eje x, cuando hablas de evolución, por lo general muestras a través del tiempo, por lo que el eje x debería srepresentar tiempo, ya sea meses, dias o años.

Los heatmaps no tiene sentido hacerlos solo con dos variables, en estos gráficos queremos comparar a travás de los colores quá variable tiene más correlación con otras y así.

>## **General**

En general hay mucho trabajo por hacer Kevin. Las ideas que tienes son increibles, sin embargo, estaria guay que pudieses hablar un lenguaje un poco mas diverso en cuanto a los temas que escribes. Es importante que Los proyectos tengan un contexto claro pero no tan extenso, que el lector no se pierda. Por otro lado, con respecto al codigo, se que puedes trabajar en ponerte mas exigente para no retrabajar, esto quiere decir hacer codigo que no sea redundante. 

Me en canta la pasion que tienes y el hecho de que le hayas puesto muchisimas ganas a todos los proyectos hasta ahora, por favor, sigue trabajando en eso, que esta muy bien, ya lo demas, es práctica. 👏👏👏👏
