### ISSUE TITLE
Xavi: BCN_Terminals_project

### ISSUE THREAD

**Issue by Xavi1250** [Ironhack-data-bcn-feb-2023/project-III-pipelines#7]
https://github.com/Xavi1250/BCN_terminals_project.git

**Comment by carlajsv** [comment]
Hola Xavi👋🏾

Te dejo los comentarios del proyecto:

>## **Organización de los archivos🧹**

Es mportante que se sigan las instrucciones del readme del repositorio del proyecto, en donde especifica las carpetas que se deben tener y los archivos, es mas entendible y es mas facil buscar a la hora de indagar en tu repo.

Deberías tener 3 carpetas: data, my-code e images

>## **README.md ✍🏽**

Esta muy bien el README Xavi, sí te diria que es importantge que lo primero que se vea es ¿qué podemos encontrar en cada archivo del repositorio? la persona que verá tu proyecto buscará los archivos de código y es importante que se pueda ubicar facilmente.

También estaría guay poner  una conclusión escrita del análisis.
De resto, excelente explicacion con los promedios sacados y la estructura en general.

>## **The code < > 👨🏽‍💻**

### Codigo_final.ipynb

Muy bien el código, mucho mas ordenado que el primero, buen uso de los comentarios.

Quizás te recomendaría hacer uso de las librerías de estadística que tenemos, es más preciso, hacerlo manualmente puede hacer que te equivoques edn los cálculos y llegues a análisis erróneos.

Hay muchos cálculos que son repetitivos, aunque modularizaste la mayoria del código, recuerda que cuando es aí, es un indicio de que es código que se puede modularizar.

### Transformacion.py

La modularización está muy muy bien. Esimportante que en los comentarios que describen a la funcion digas que parámetros y de qué tipo recibe la funcion y qué objeto devuelve.

> ## **Visualizaciones 🎨**

En cuanto a los gráficos, esta vez hubo muchisimas mejoras, estuvo muy bien que usaras los mismos colores y que haya concordancia en todo el análisis, asi como colores que hacen contraste para poder diferenciar entre unas barras y otras.

>## **General**

En general me ha gustado mucho tu proyecto, hay una mejora importante con respecto a los anteriores, te felicito!
