### ISSUE TITLE
Augusto - Project  2: Financial Analysis

### ISSUE THREAD

**Issue by augustomues** [Ironhack-data-bcn-feb-2023/project-III-pipelines#9]
https://github.com/augustomues/Project-2

**Comment by carlajsv** [comment]
Hola Augusto👋🏾

Te dejo los comentarios del proyecto:

>## **Organización de los archivos🧹**

Guay la organización de los archivos, si te diría que el archivo .py por lo general se llama src.py, pero muy bien porque modularizaste. 

Recuerda la próxima crear una carpeta de my-code con los archivos de código y llamar los archivos como se pone en la descripción del proyecto para que sea más fácil de entender.

>## **README.md ✍🏽**

El README muy bien trabajado, es importante que a primera instancia explique qué hay en cada archivo que código, de forma que las personas que lo vayan a revisar, sepan en donde buscar. Ese es uno de los aspectos mas nimportantes del README.

No hace falta que lleve índice, es importante que sea breve, recuerda: menos es más.

>## **The code < > 👨🏽‍💻**

### main.ipynb

No hace falta hacer el mismo indice que en el README ni colocar el mismo texto, recuerda que el README esta para entender el proyecto y al entrar al código, ya la persona debería saber de que hablas.

Excelente el uso de SQL a través de python

### modularization.py

Gracias por modularizar, te felicito por esto. Recuerda que las funciones deben tener los comentarios explicativos de que hace cada funcion, que parámetros recibe y que tipo de objeto arroja (como la primera del archivo)

> ## **Visualizaciones 🎨**

Recuerda porfa modificar las etiquetas de los ejes de los gráficos, es importante que tengan nocbre entendibles y no los que vienen por default.

Muy bien que hayas puesto colores que se contraresten entre si, ayuda a entender los gráficos de forma más clara.

Estaría guay una leyenda de lo que significan las siglas relacionadas con el tema a tratar, ya que hay gente que leerá y no sabrá que significa cada cosa en los graficos.

>## **General**

En general muy bien el proyecto, si te diría que de cara a mostrarlo como curriculum, modifiques las cosas de los comentarios que te pongo mas arriba.

También, recuerda seguir las instrucciones del readme del repo del proyecto.

Felicidades por el proyecto, muy buen esfuerzo invertido
